### ISSUE TITLE
XM Bugs - Lowpass Filter gets stuck

### ISSUE THREAD

**Issue by steffest** [steffest/BassoonTracker#10]
Split from #8 

Some songs have a bug where a lowpass filter is enabled and remains even after loading new songs (gets "stuck"):

vogue-ambient light.zip (Pattern 9)
lesnik-hot dogs 3.xm (happens immediately in Pattern 1)
lamb-happiness.xm (happens at very end of Pattern 1)
That requires refreshing the page to fix, so pretty bad.

**Comment by bryc** [comment]
Looking into this more: The issue comes from **E0x** effect (Amiga filter). That shouldn't even work in FT2 XM mode (just backwards compatibility for MODs), and according to some documentation, should only work in .MOD when x = 1. Those example files all use "E00" (x = 0) which actually should turn the filter off!

**Comment by steffest** [comment]
It's the other way around actually: E00 turns the filter on, E01 turns it off (see e.g. docs on https://github.com/cmatsuoka/tracker-history/blob/master/reference/amiga/protracker/Protracker_v2.0a/PTEffects.txt but I also just checked this on a real amiga to be sure)
But you are right that XM files should ignore it: even Digibooster on the amiga - which can read and write xm files - ignores it.
It's updated now.
