### ISSUE TITLE
Unable to load from personal domain

### ISSUE THREAD

**Issue by rogalian** [steffest/BassoonTracker#61]
I've thrown a load of files in https://rogalian.com/mod

I can't get any of them to load. E.g. https://www.stef.be/bassoontracker/?file=https://rogalian.com/mod/cls-yell.mod

nginx's access log looks fine:
`165.225.196.82 - - [18/Nov/2020:14:11:30 +0000] "GET /mod/cls-yell.mod HTTP/1.1" 200 10240 "https://www.stef.be/bassoontracker/?file=https://rogalian.com/mod/cls-yell.mod" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0" "-"`

**Comment by steffest** [comment]
You can see the error message in bassoontracker when you open the console log (F12)

![image](https://user-images.githubusercontent.com/763047/99589385-339ed500-29ec-11eb-8dc1-cb464cfc90c4.png)

Javascript needs CORS permission from the server to be able to load resources from another domain.
There are 3 ways to solve this.

1. Preferred solution: enable the CORS headers on your server
2. There's an undocumented feature to proxy external resources through the bassoontracker server. The url is then 
https://www.stef.be/bassoontracker/?file=api/proxy?https://rogalian.com/mod/cls-yell.mod 
Loading is a bit slower then because the file has to pass through some additional hoops. This works because the server then requests the file and passes it to the client, circumventing the cross-domain loading.
3. use the http:// version of your domain instead of https:// - this seems weird but http:// links are always proxied (because a page on https:// can't load http:// resources in javascript) so in you case, urls like https://www.stef.be/bassoontracker/?file=http://rogalian.com/mod/cls-yell.mod also work

**Comment by rogalian** [comment]
Brilliant, thank you! Not a web dev so I didn't think to look in the console. I'll go with the CORS headers. I swear I tried the http:// version first (server's https certs had expired) but I'd prefer not to proxy if possible.

Of course I could host the software directly... 👍
